from contextlib import suppress

config = {
    "CHAIN": "",
    "SERVICE_CONFIG": {
        "rule": "",
    },
    "STORAGE_CONFIG": {
        "doris": {
            "client1": {
                "host": "",
                "port": 9030,
                "user": "",
                "password": "",
            },
            "client2": {
                "host": "",
                "port": 9030,
                "user": "",
                "password": "",
            },
            "dbs": ["address", "stats"],
            "data_map": {
                # 地址余额
                "balance": {
                    "btc": {"db": "address", "table": "btc_address_balance"},
                    "eth": {"db": "address", "table": "eth_address_balance"},
                    "bsc": {"db": "address", "table": "bsc_address_balance"},
                    "tron": {"db": "address", "table": "tron_address_balance"},
                    "polygon": {"db": "address", "table": "polygon_address_balance"},
                    "avalanche": {"db": "address", "table": "avalanche_address_balance"},
                    "klaytn": {"db": "address", "table": "klaytn_address_balance"},
                    "arbitrum": {"db": "address", "table": "arbitrum_address_balance"},
                    "optimism": {"db": "address", "table": "optimism_address_balance"},
                    "zksync": {"db": "address", "table": "zksync_address_balance"},
                    "ltc": {"db": "address", "table": "ltc_address_balance"},
                    "aptos": {"db": "address", "table": "aptos_address_balance"},
                    "solana": {"db": "address", "table": "solana_address_balance"},
                    "xrp": {"db": "address", "table": "xrp_address_balance"},
                    "ton": {"db": "address", "table": "ton_address_balance"},
                    "iotex": {"db": "address", "table": "iotex_address_balance"},
                    "hsk": {"db": "address", "table": "hsk_address_balance"},
                    "doge": {"db": "address", "table": "doge_address_balance"},
                    "conflux": {"db": "address", "table": "conflux_address_balance"},
                    "base": {"db": "address", "table": "base_address_balance"},
                },
                # 地址统计信息
                "addr_stats": {
                    "btc": {"db": "stats", "table": "btc_addr_stats"},
                    "eth": {"db": "stats", "table": "eth_addr_stats"},
                    "bsc": {"db": "stats", "table": "bsc_addr_stats"},
                    "tron": {"db": "stats", "table": "tron_addr_stats"},
                    "polygon": {"db": "stats", "table": "polygon_addr_stats"},
                    "avalanche": {"db": "stats", "table": "avalanche_addr_stats"},
                    "klaytn": {"db": "stats", "table": "klaytn_addr_stats"},
                    "arbitrum": {"db": "stats", "table": "arbitrum_addr_stats"},
                    "optimism": {"db": "stats", "table": "optimism_addr_stats"},
                    "zksync": {"db": "stats", "table": "zksync_addr_stats"},
                    "ltc": {"db": "stats", "table": "ltc_addr_stats"},
                    "aptos": {"db": "stats", "table": "aptos_addr_stats"},
                    "solana": {"db": "stats", "table": "solana_addr_stats"},
                    "xrp": {"db": "stats", "table": "xrp_addr_stats"},
                    "ton": {"db": "stats", "table": "ton_addr_stats"},
                    "iotex": {"db": "stats", "table": "iotex_addr_stats"},
                    "hsk": {"db": "stats", "table": "hsk_addr_stats"},
                    "doge": {"db": "stats", "table": "doge_addr_stats"},
                    "conflux": {"db": "stats", "table": "conflux_addr_stats"},
                    "base": {"db": "stats", "table": "base_addr_stats"},
                },
                # 每日交易对手
                "daily_pair": {
                    "eth": {"db": "stats", "table": "eth_mixin_daily_pair"},
                    "bsc": {"db": "stats", "table": "bsc_mixin_daily_pair"},
                    "tron": {"db": "stats", "table": "tron_mixin_daily_pair"},
                    "polygon": {"db": "stats", "table": "polygon_mixin_daily_pair"},
                    "avalanche": {"db": "stats", "table": "avalanche_mixin_daily_pair"},
                    "klaytn": {"db": "stats", "table": "klaytn_mixin_daily_pair"},
                    "arbitrum": {"db": "stats", "table": "arbitrum_mixin_daily_pair"},
                    "optimism": {"db": "stats", "table": "optimism_mixin_daily_pair"},
                    "zksync": {"db": "stats", "table": "zksync_mixin_daily_pair"},
                    "aptos": {"db": "stats", "table": "aptos_mixin_daily_pair"},
                    "solana": {"db": "stats", "table": "solana_mixin_daily_pair"},
                    "xrp": {"db": "stats", "table": "xrp_mixin_daily_pair"},
                    "ton": {"db": "stats", "table": "ton_mixin_daily_pair"},
                    "iotex": {"db": "stats", "table": "iotex_mixin_daily_pair"},
                    "hsk": {"db": "stats", "table": "hsk_mixin_daily_pair"},
                    "conflux": {"db": "stats", "table": "conflux_mixin_daily_pair"},
                    "base": {"db": "stats", "table": "base_mixin_daily_pair"},
                },
                # 全量交易对手
                "full_pair": {
                    "eth": {"db": "stats", "table": "eth_mixin_full_pair"},
                    "bsc": {"db": "stats", "table": "bsc_mixin_full_pair"},
                    "tron": {"db": "stats", "table": "tron_mixin_full_pair"},
                    "polygon": {"db": "stats", "table": "polygon_mixin_full_pair"},
                    "avalanche": {"db": "stats", "table": "avalanche_mixin_full_pair"},
                    "klaytn": {"db": "stats", "table": "klaytn_mixin_full_pair"},
                    "arbitrum": {"db": "stats", "table": "arbitrum_mixin_full_pair"},
                    "optimism": {"db": "stats", "table": "optimism_mixin_full_pair"},
                    "zksync": {"db": "stats", "table": "zksync_mixin_full_pair"},
                    "aptos": {"db": "stats", "table": "aptos_mixin_full_pair"},
                    "solana": {"db": "stats", "table": "solana_mixin_full_pair"},
                    "xrp": {"db": "stats", "table": "xrp_mixin_full_pair"},
                    "ton": {"db": "stats", "table": "ton_mixin_full_pair"},
                    "iotex": {"db": "stats", "table": "iotex_mixin_full_pair"},
                    "hsk": {"db": "stats", "table": "hsk_mixin_full_pair"},
                    "conflux": {"db": "stats", "table": "conflux_mixin_full_pair"},
                    "base": {"db": "stats", "table": "base_mixin_full_pair"},
                },
            },
        },
        "es": {
            "client1": {
                "hosts": "",
            },
            "client2": {
                "hosts": "",
            },
            "data_map": {
                # 本币交易
                "tx": {
                    "btc": "btc_tx_behavior",
                    "eth": "eth_tx_behavior",
                    "bsc": "bsc_tx_behavior",
                    "tron": "tron_tx_behavior",
                    "polygon": "polygon_tx_behavior",
                    "avalanche": "avalanche_tx_behavior",
                    "klaytn": "klaytn_tx_behavior",
                    "arbitrum": "arbitrum_tx_behavior",
                    "optimism": "optimism_tx_behavior",
                    "zksync": "zksync_tx_behavior",
                    "ltc": "ltc_tx_behavior",
                    "aptos": "aptos_tx_behavior",
                    "solana": "solana_tx_behavior",
                    "xrp": "xrp_tx_behavior",
                    "ton": "ton_tx_behavior",
                    "iotex": "iotex_tx_behavior",
                    "hsk": "hsk_tx_behavior",
                    "doge": "doge_tx_behavior",
                    "conflux": "conflux_tx_behavior",
                    "base": "base_tx_behavior",
                },
                # 内部交易
                "inner_tx": {
                    "eth": "eth_inner_tx_behavior",
                    "bsc": "bsc_inner_tx_behavior",
                    "tron": "tron_inner_tx_behavior",
                    "polygon": "polygon_inner_tx_behavior",
                    "avalanche": "avalanche_inner_tx_behavior",
                    "klaytn": "klaytn_inner_tx_behavior",
                    "arbitrum": "arbitrum_inner_tx_behavior",
                    "optimism": "optimism_inner_tx_behavior",
                    "iotex": "iotex_inner_tx_behavior",
                    "hsk": "hsk_inner_tx_behavior",
                    "conflux": "conflux_inner_tx_behavior",
                    "base": "base_inner_tx_behavior",
                },
                # 代币交易
                "transfer": {
                    "eth": "eth_transfer_behavior",
                    "bsc": "bsc_transfer_behavior",
                    "tron": "tron_transfer_behavior",
                    "polygon": "polygon_transfer_behavior",
                    "avalanche": "avalanche_transfer_behavior",
                    "klaytn": "klaytn_transfer_behavior",
                    "arbitrum": "arbitrum_transfer_behavior",
                    "optimism": "optimism_transfer_behavior",
                    "zksync": "zksync_transfer_behavior",
                    "aptos": "aptos_transfer_behavior",
                    "solana": "solana_transfer_behavior",
                    "xrp": "xrp_transfer_behavior",
                    "ton": "ton_transfer_behavior",
                    "iotex": "iotex_transfer_behavior",
                    "hsk": "hsk_transfer_behavior",
                    "conflux": "conflux_transfer_behavior",
                    "base": "base_transfer_behavior",
                },
                # 兑币行为
                "swap": {
                    "eth": "eth_swap_behavior",
                    "bsc": "bsc_swap_behavior",
                    "tron": "tron_swap_behavior",
                    "polygon": "polygon_swap_behavior",
                    "avalanche": "avalanche_swap_behavior",
                    "klaytn": "klaytn_swap_behavior",
                    "arbitrum": "arbitrum_swap_behavior",
                    "optimism": "optimism_swap_behavior",
                    "zksync": "zksync_swap_behavior",
                    "solana": "solana_swap_behavior",
                    "xrp": "xrp_swap_behavior",
                    "iotex": "iotex_swap_behavior",
                    "hsk": "hsk_swap_behavior",
                    "conflux": "conflux_swap_behavior",
                    "base": "base_swap_behavior",
                },
                # 跨链行为
                "cross": {
                    "eth": "eth_cross_behavior",
                    "bsc": "bsc_cross_behavior",
                    "tron": "tron_cross_behavior",
                    "polygon": "polygon_cross_behavior",
                    "avalanche": "avalanche_cross_behavior",
                    "klaytn": "klaytn_cross_behavior",
                    "arbitrum": "arbitrum_cross_behavior",
                    "optimism": "optimism_cross_behavior",
                    "zksync": "zksync_cross_behavior",
                    "solana": "solana_cross_behavior",
                    "ton": "ton_cross_behavior",
                    "iotex": "iotex_cross_behavior",
                    "hsk": "hsk_cross_behavior",
                    "conflux": "conflux_cross_behavior",
                    "base": "base_cross_behavior",
                },
            },
        },
        "mongodb": {
            "data": {
                "client": {
                    "uri": "mongodb://",
                },
                "data_map": {
                    # 代币表
                    "token": {
                        "btc": {"db": "btc", "collection": "token_v3"},
                        "eth": {"db": "eth", "collection": "token_v3"},
                        "bsc": {"db": "bsc", "collection": "token_v3"},
                        "polygon": {"db": "polygon", "collection": "token_v3"},
                        "tron": {"db": "tron", "collection": "token_v3"},
                        "avalanche": {"db": "avalanche", "collection": "token_v3"},
                        "klaytn": {"db": "klaytn", "collection": "token_v3"},
                        "arbitrum": {"db": "arbitrum", "collection": "token_v3"},
                        "optimism": {"db": "optimism", "collection": "token_v3"},
                        "zksync": {"db": "zksync", "collection": "token_v3"},
                        "ltc": {"db": "ltc", "collection": "token_v3"},
                        "aptos": {"db": "aptos", "collection": "token_v3"},
                        "solana": {"db": "solana", "collection": "token_v3"},
                        "xrp": {"db": "xrp", "collection": "token_v3"},
                        "ton": {"db": "ton", "collection": "token_v3"},
                        "iotex": {"db": "iotex", "collection": "token_v3"},
                        "hsk": {"db": "hsk", "collection": "token_v3"},
                        "doge": {"db": "doge", "collection": "token_v3"},
                        "conflux": {"db": "conflux", "collection": "token_v3"},
                        "base": {"db": "base", "collection": "token_v3"},
                    },
                    # 合约表
                    "contract": {
                        "btc": {"db": "btc", "collection": "contract_base"},
                        "eth": {"db": "eth", "collection": "contract_base"},
                        "bsc": {"db": "bsc", "collection": "contract_base"},
                        "polygon": {"db": "polygon", "collection": "contract_base"},
                        "tron": {"db": "tron", "collection": "contract_base"},
                        "avalanche": {"db": "avalanche", "collection": "contract_base"},
                        "klaytn": {"db": "klaytn", "collection": "contract_base"},
                        "arbitrum": {"db": "arbitrum", "collection": "contract_base"},
                        "optimism": {"db": "optimism", "collection": "contract_base"},
                        "zksync": {"db": "zksync", "collection": "contract_base"},
                        "ltc": {"db": "ltc", "collection": "contract_base"},
                        "aptos": {"db": "aptos", "collection": "contract_base"},
                        "solana": {"db": "solana", "collection": "contract_base"},
                        "xrp": {"db": "xrp", "collection": "contract_base"},
                        "ton": {"db": "ton", "collection": "contract_base"},
                        "iotex": {"db": "iotex", "collection": "contract_base"},
                        "hsk": {"db": "hsk", "collection": "contract_base"},
                        "doge": {"db": "doge", "collection": "contract_base"},
                        "conflux": {"db": "conflux", "collection": "contract_base"},
                        "base": {"db": "base", "collection": "contract_base"},
                    },
                    # LP 池子代币表
                    "lp": {
                        "eth": {"db": "eth", "collection": "liquid_pair_token"},
                        "bsc": {"db": "bsc", "collection": "liquid_pair_token"},
                        "polygon": {"db": "polygon", "collection": "liquid_pair_token"},
                        "tron": {"db": "tron", "collection": "liquid_pair_token"},
                        "avalanche": {"db": "avalanche", "collection": "liquid_pair_token"},
                        "klaytn": {"db": "klaytn", "collection": "liquid_pair_token"},
                        "arbitrum": {"db": "arbitrum", "collection": "liquid_pair_token"},
                        "optimism": {"db": "optimism", "collection": "liquid_pair_token"},
                        "zksync": {"db": "zksync", "collection": "liquid_pair_token"},
                        "solana": {"db": "solana", "collection": "liquid_pair_token"},
                        # "iotex": {"db": "iotex", "collection": "liquid_pair_token"},
                        "hsk": {"db": "hsk", "collection": "liquid_pair_token"},
                        "conflux": {"db": "conflux", "collection": "liquid_pair_token"},
                        "base": {"db": "base", "collection": "liquid_pair_token"},
                    },
                    "address_entity": {
                        "btc": {"db": "btc_entity", "collection": "address_entity"},
                    },
                    "change_msg": {
                        "btc": {"db": "btc_entity", "collection": "change_msg"},
                    },
                    "entity": {
                        "btc": {"db": "btc_entity", "collection": "entity"},
                    },
                    # 可信币表
                    "reliable_token": {
                        "*": {"db": "chain_info", "collection": "reliable_token"},
                    },
                },
            },
        },
        "tag_api": {
            "url": "",
            "token": "",
        },
        "chain_instance_mapping": {
            # 不同链的数据存在不同的 es/doris 实例上，这里管理映射表
            "btc": "client1",
            "eth": "client1",
            "bsc": "client1",
            "tron": "client1",
            "polygon": "client2",
            "avalanche": "client2",
            "klaytn": "client2",
            "arbitrum": "client2",
            "optimism": "client2",
            "zksync": "client2",
            "ltc": "client2",
            "aptos": "client2",
            "solana": "client2",
            "xrp": "client2",
            "ton": "client2",
            "iotex": "client2",
            "hsk": "client2",
            "doge": "client2",
            "conflux": "client2",
            "base": "client2",
        },
    },
    "THRESHOLD_CONFIG": {},
}

with suppress(Exception):
    from local_config import config as local_config
    from nb_util.type_conversion import update_dict

    config = update_dict(config, local_config)
